//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_Informe.tablaValesTransporte {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public partial class AxdType_DimensionAttributeValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public partial class AxdType_DimensionAttributeValueSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AxdType_DimensionAttributeValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable=false)]
        public AxdType_DimensionAttributeValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/TransportTicket")]
    public partial class AxdEntity_TransportTicketTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private string agencyIdField;
        
        private string businessUnitField;
        
        private string conductorIdField;
        
        private string contractAgencyField;
        
        private string costCenterField;
        
        private System.Nullable<AxdExtType_NoYesId> costeExcedidoField;
        
        private bool costeExcedidoFieldSpecified;
        
        private string currencyCodeField;
        
        private AxdType_DimensionAttributeValueSet defaultDimensionField;
        
        private string delegacionField;
        
        private System.Nullable<System.DateTime> deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private System.Nullable<AxdExtType_Grua> gruaField;
        
        private bool gruaFieldSpecified;
        
        private System.Nullable<decimal> horasEsperaField;
        
        private bool horasEsperaFieldSpecified;
        
        private System.Nullable<decimal> horasGruaField;
        
        private bool horasGruaFieldSpecified;
        
        private string identifyOrigField;
        
        private System.Nullable<decimal> importeValesField;
        
        private bool importeValesFieldSpecified;
        
        private string inventLocationIdField;
        
        private System.Nullable<System.DateTime> invoiceDateField;
        
        private bool invoiceDateFieldSpecified;
        
        private string invoiceIdField;
        
        private System.Nullable<decimal> kmField;
        
        private bool kmFieldSpecified;
        
        private string matriculaField;
        
        private string matriculaRemolqueField;
        
        private System.Nullable<AxdEnum_TransportTicketReason> motivoValeTransporteField;
        
        private bool motivoValeTransporteFieldSpecified;
        
        private System.Nullable<decimal> netWeightField;
        
        private bool netWeightFieldSpecified;
        
        private string obraIdField;
        
        private string observacionesField;
        
        private string officialNumberField;
        
        private string packingSlipIdField;
        
        private System.Nullable<decimal> portesEsperaField;
        
        private bool portesEsperaFieldSpecified;
        
        private System.Nullable<decimal> portesGruaField;
        
        private bool portesGruaFieldSpecified;
        
        private System.Nullable<AxdExtType_Posted> postedField;
        
        private bool postedFieldSpecified;
        
        private System.Nullable<decimal> priceKgKmField;
        
        private bool priceKgKmFieldSpecified;
        
        private string purchCompanyField;
        
        private string purchIdField;
        
        private System.Nullable<long> recIdField;
        
        private bool recIdFieldSpecified;
        
        private System.Nullable<int> recVersionField;
        
        private bool recVersionFieldSpecified;
        
        private System.Nullable<AxdEnum_SalesOTransfer> salesOTransferField;
        
        private bool salesOTransferFieldSpecified;
        
        private System.Nullable<AxdExtType_NoYesId> seleccionadoField;
        
        private bool seleccionadoFieldSpecified;
        
        private System.Nullable<decimal> temporaryWeightField;
        
        private bool temporaryWeightFieldSpecified;
        
        private string tipoTransIdField;
        
        private System.Nullable<decimal> toneladasField;
        
        private bool toneladasFieldSpecified;
        
        private System.Nullable<decimal> toneladasAlbaranField;
        
        private bool toneladasAlbaranFieldSpecified;
        
        private System.Nullable<decimal> tonelajeContratadoField;
        
        private bool tonelajeContratadoFieldSpecified;
        
        private string transportContainerField;
        
        private string transportistaIdField;
        
        private System.Nullable<int> transportNumPackageField;
        
        private bool transportNumPackageFieldSpecified;
        
        private string transportSealField;
        
        private AxdEnum_TransportTicketType transportTicketTypeField;
        
        private string transportTicketUnionField;
        
        private System.Nullable<AxdEnum_TypeTransportTicket> typeTransportTicketField;
        
        private bool typeTransportTicketFieldSpecified;
        
        private System.Nullable<decimal> uPSField;
        
        private bool uPSFieldSpecified;
        
        private string vendorPackingSlipIdField;
        
        private string yourVendNumberField;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_TransportTicketTable() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AgencyId {
            get {
                return this.agencyIdField;
            }
            set {
                this.agencyIdField = value;
                this.RaisePropertyChanged("AgencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string BusinessUnit {
            get {
                return this.businessUnitField;
            }
            set {
                this.businessUnitField = value;
                this.RaisePropertyChanged("BusinessUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ConductorId {
            get {
                return this.conductorIdField;
            }
            set {
                this.conductorIdField = value;
                this.RaisePropertyChanged("ConductorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ContractAgency {
            get {
                return this.contractAgencyField;
            }
            set {
                this.contractAgencyField = value;
                this.RaisePropertyChanged("ContractAgency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CostCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
                this.RaisePropertyChanged("CostCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<AxdExtType_NoYesId> CosteExcedido {
            get {
                return this.costeExcedidoField;
            }
            set {
                this.costeExcedidoField = value;
                this.RaisePropertyChanged("CosteExcedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CosteExcedidoSpecified {
            get {
                return this.costeExcedidoFieldSpecified;
            }
            set {
                this.costeExcedidoFieldSpecified = value;
                this.RaisePropertyChanged("CosteExcedidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("CurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public AxdType_DimensionAttributeValueSet DefaultDimension {
            get {
                return this.defaultDimensionField;
            }
            set {
                this.defaultDimensionField = value;
                this.RaisePropertyChanged("DefaultDimension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Delegacion {
            get {
                return this.delegacionField;
            }
            set {
                this.delegacionField = value;
                this.RaisePropertyChanged("Delegacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
                this.RaisePropertyChanged("DeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<AxdExtType_Grua> Grua {
            get {
                return this.gruaField;
            }
            set {
                this.gruaField = value;
                this.RaisePropertyChanged("Grua");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GruaSpecified {
            get {
                return this.gruaFieldSpecified;
            }
            set {
                this.gruaFieldSpecified = value;
                this.RaisePropertyChanged("GruaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> HorasEspera {
            get {
                return this.horasEsperaField;
            }
            set {
                this.horasEsperaField = value;
                this.RaisePropertyChanged("HorasEspera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HorasEsperaSpecified {
            get {
                return this.horasEsperaFieldSpecified;
            }
            set {
                this.horasEsperaFieldSpecified = value;
                this.RaisePropertyChanged("HorasEsperaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> HorasGrua {
            get {
                return this.horasGruaField;
            }
            set {
                this.horasGruaField = value;
                this.RaisePropertyChanged("HorasGrua");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HorasGruaSpecified {
            get {
                return this.horasGruaFieldSpecified;
            }
            set {
                this.horasGruaFieldSpecified = value;
                this.RaisePropertyChanged("HorasGruaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string IdentifyOrig {
            get {
                return this.identifyOrigField;
            }
            set {
                this.identifyOrigField = value;
                this.RaisePropertyChanged("IdentifyOrig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> ImporteVales {
            get {
                return this.importeValesField;
            }
            set {
                this.importeValesField = value;
                this.RaisePropertyChanged("ImporteVales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImporteValesSpecified {
            get {
                return this.importeValesFieldSpecified;
            }
            set {
                this.importeValesFieldSpecified = value;
                this.RaisePropertyChanged("ImporteValesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string InventLocationId {
            get {
                return this.inventLocationIdField;
            }
            set {
                this.inventLocationIdField = value;
                this.RaisePropertyChanged("InventLocationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceDateSpecified {
            get {
                return this.invoiceDateFieldSpecified;
            }
            set {
                this.invoiceDateFieldSpecified = value;
                this.RaisePropertyChanged("InvoiceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
                this.RaisePropertyChanged("InvoiceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> Km {
            get {
                return this.kmField;
            }
            set {
                this.kmField = value;
                this.RaisePropertyChanged("Km");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KmSpecified {
            get {
                return this.kmFieldSpecified;
            }
            set {
                this.kmFieldSpecified = value;
                this.RaisePropertyChanged("KmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string Matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
                this.RaisePropertyChanged("Matricula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string MatriculaRemolque {
            get {
                return this.matriculaRemolqueField;
            }
            set {
                this.matriculaRemolqueField = value;
                this.RaisePropertyChanged("MatriculaRemolque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<AxdEnum_TransportTicketReason> MotivoValeTransporte {
            get {
                return this.motivoValeTransporteField;
            }
            set {
                this.motivoValeTransporteField = value;
                this.RaisePropertyChanged("MotivoValeTransporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MotivoValeTransporteSpecified {
            get {
                return this.motivoValeTransporteFieldSpecified;
            }
            set {
                this.motivoValeTransporteFieldSpecified = value;
                this.RaisePropertyChanged("MotivoValeTransporteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<decimal> NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
                this.RaisePropertyChanged("NetWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetWeightSpecified {
            get {
                return this.netWeightFieldSpecified;
            }
            set {
                this.netWeightFieldSpecified = value;
                this.RaisePropertyChanged("NetWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string ObraId {
            get {
                return this.obraIdField;
            }
            set {
                this.obraIdField = value;
                this.RaisePropertyChanged("ObraId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("Observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string OfficialNumber {
            get {
                return this.officialNumberField;
            }
            set {
                this.officialNumberField = value;
                this.RaisePropertyChanged("OfficialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string PackingSlipId {
            get {
                return this.packingSlipIdField;
            }
            set {
                this.packingSlipIdField = value;
                this.RaisePropertyChanged("PackingSlipId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<decimal> PortesEspera {
            get {
                return this.portesEsperaField;
            }
            set {
                this.portesEsperaField = value;
                this.RaisePropertyChanged("PortesEspera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortesEsperaSpecified {
            get {
                return this.portesEsperaFieldSpecified;
            }
            set {
                this.portesEsperaFieldSpecified = value;
                this.RaisePropertyChanged("PortesEsperaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<decimal> PortesGrua {
            get {
                return this.portesGruaField;
            }
            set {
                this.portesGruaField = value;
                this.RaisePropertyChanged("PortesGrua");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortesGruaSpecified {
            get {
                return this.portesGruaFieldSpecified;
            }
            set {
                this.portesGruaFieldSpecified = value;
                this.RaisePropertyChanged("PortesGruaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<AxdExtType_Posted> Posted {
            get {
                return this.postedField;
            }
            set {
                this.postedField = value;
                this.RaisePropertyChanged("Posted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostedSpecified {
            get {
                return this.postedFieldSpecified;
            }
            set {
                this.postedFieldSpecified = value;
                this.RaisePropertyChanged("PostedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> PriceKgKm {
            get {
                return this.priceKgKmField;
            }
            set {
                this.priceKgKmField = value;
                this.RaisePropertyChanged("PriceKgKm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceKgKmSpecified {
            get {
                return this.priceKgKmFieldSpecified;
            }
            set {
                this.priceKgKmFieldSpecified = value;
                this.RaisePropertyChanged("PriceKgKmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string PurchCompany {
            get {
                return this.purchCompanyField;
            }
            set {
                this.purchCompanyField = value;
                this.RaisePropertyChanged("PurchCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string PurchId {
            get {
                return this.purchIdField;
            }
            set {
                this.purchIdField = value;
                this.RaisePropertyChanged("PurchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<long> RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
                this.RaisePropertyChanged("RecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecIdSpecified {
            get {
                return this.recIdFieldSpecified;
            }
            set {
                this.recIdFieldSpecified = value;
                this.RaisePropertyChanged("RecIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<int> RecVersion {
            get {
                return this.recVersionField;
            }
            set {
                this.recVersionField = value;
                this.RaisePropertyChanged("RecVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecVersionSpecified {
            get {
                return this.recVersionFieldSpecified;
            }
            set {
                this.recVersionFieldSpecified = value;
                this.RaisePropertyChanged("RecVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<AxdEnum_SalesOTransfer> SalesOTransfer {
            get {
                return this.salesOTransferField;
            }
            set {
                this.salesOTransferField = value;
                this.RaisePropertyChanged("SalesOTransfer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesOTransferSpecified {
            get {
                return this.salesOTransferFieldSpecified;
            }
            set {
                this.salesOTransferFieldSpecified = value;
                this.RaisePropertyChanged("SalesOTransferSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<AxdExtType_NoYesId> Seleccionado {
            get {
                return this.seleccionadoField;
            }
            set {
                this.seleccionadoField = value;
                this.RaisePropertyChanged("Seleccionado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeleccionadoSpecified {
            get {
                return this.seleccionadoFieldSpecified;
            }
            set {
                this.seleccionadoFieldSpecified = value;
                this.RaisePropertyChanged("SeleccionadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<decimal> TemporaryWeight {
            get {
                return this.temporaryWeightField;
            }
            set {
                this.temporaryWeightField = value;
                this.RaisePropertyChanged("TemporaryWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemporaryWeightSpecified {
            get {
                return this.temporaryWeightFieldSpecified;
            }
            set {
                this.temporaryWeightFieldSpecified = value;
                this.RaisePropertyChanged("TemporaryWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string TipoTransId {
            get {
                return this.tipoTransIdField;
            }
            set {
                this.tipoTransIdField = value;
                this.RaisePropertyChanged("TipoTransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<decimal> Toneladas {
            get {
                return this.toneladasField;
            }
            set {
                this.toneladasField = value;
                this.RaisePropertyChanged("Toneladas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToneladasSpecified {
            get {
                return this.toneladasFieldSpecified;
            }
            set {
                this.toneladasFieldSpecified = value;
                this.RaisePropertyChanged("ToneladasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<decimal> ToneladasAlbaran {
            get {
                return this.toneladasAlbaranField;
            }
            set {
                this.toneladasAlbaranField = value;
                this.RaisePropertyChanged("ToneladasAlbaran");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToneladasAlbaranSpecified {
            get {
                return this.toneladasAlbaranFieldSpecified;
            }
            set {
                this.toneladasAlbaranFieldSpecified = value;
                this.RaisePropertyChanged("ToneladasAlbaranSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<decimal> TonelajeContratado {
            get {
                return this.tonelajeContratadoField;
            }
            set {
                this.tonelajeContratadoField = value;
                this.RaisePropertyChanged("TonelajeContratado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TonelajeContratadoSpecified {
            get {
                return this.tonelajeContratadoFieldSpecified;
            }
            set {
                this.tonelajeContratadoFieldSpecified = value;
                this.RaisePropertyChanged("TonelajeContratadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string TransportContainer {
            get {
                return this.transportContainerField;
            }
            set {
                this.transportContainerField = value;
                this.RaisePropertyChanged("TransportContainer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string TransportistaId {
            get {
                return this.transportistaIdField;
            }
            set {
                this.transportistaIdField = value;
                this.RaisePropertyChanged("TransportistaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public System.Nullable<int> TransportNumPackage {
            get {
                return this.transportNumPackageField;
            }
            set {
                this.transportNumPackageField = value;
                this.RaisePropertyChanged("TransportNumPackage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransportNumPackageSpecified {
            get {
                return this.transportNumPackageFieldSpecified;
            }
            set {
                this.transportNumPackageFieldSpecified = value;
                this.RaisePropertyChanged("TransportNumPackageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public string TransportSeal {
            get {
                return this.transportSealField;
            }
            set {
                this.transportSealField = value;
                this.RaisePropertyChanged("TransportSeal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public AxdEnum_TransportTicketType TransportTicketType {
            get {
                return this.transportTicketTypeField;
            }
            set {
                this.transportTicketTypeField = value;
                this.RaisePropertyChanged("TransportTicketType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public string TransportTicketUnion {
            get {
                return this.transportTicketUnionField;
            }
            set {
                this.transportTicketUnionField = value;
                this.RaisePropertyChanged("TransportTicketUnion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public System.Nullable<AxdEnum_TypeTransportTicket> TypeTransportTicket {
            get {
                return this.typeTransportTicketField;
            }
            set {
                this.typeTransportTicketField = value;
                this.RaisePropertyChanged("TypeTransportTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeTransportTicketSpecified {
            get {
                return this.typeTransportTicketFieldSpecified;
            }
            set {
                this.typeTransportTicketFieldSpecified = value;
                this.RaisePropertyChanged("TypeTransportTicketSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public System.Nullable<decimal> UPS {
            get {
                return this.uPSField;
            }
            set {
                this.uPSField = value;
                this.RaisePropertyChanged("UPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPSSpecified {
            get {
                return this.uPSFieldSpecified;
            }
            set {
                this.uPSFieldSpecified = value;
                this.RaisePropertyChanged("UPSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public string VendorPackingSlipId {
            get {
                return this.vendorPackingSlipIdField;
            }
            set {
                this.vendorPackingSlipIdField = value;
                this.RaisePropertyChanged("VendorPackingSlipId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public string YourVendNumber {
            get {
                return this.yourVendNumberField;
            }
            set {
                this.yourVendNumberField = value;
                this.RaisePropertyChanged("YourVendNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdExtType_NoYesId {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdExtType_Grua {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_TransportTicketReason {
        
        /// <remarks/>
        NoExplicacion,
        
        /// <remarks/>
        ErrorRecuento,
        
        /// <remarks/>
        DestinoNoHabitual,
        
        /// <remarks/>
        ErrorImputableTransportista,
        
        /// <remarks/>
        EsperaCargaDescarga,
        
        /// <remarks/>
        Urgencia,
        
        /// <remarks/>
        NoReparto,
        
        /// <remarks/>
        FaltaMaterial,
        
        /// <remarks/>
        ErrorClienteDevolucion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdExtType_Posted {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_SalesOTransfer {
        
        /// <remarks/>
        Sales,
        
        /// <remarks/>
        Transfer,
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        PackingSlipDevolution,
        
        /// <remarks/>
        Purch,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_TransportTicketType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Purchs,
        
        /// <remarks/>
        Logistics,
        
        /// <remarks/>
        Obra,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_TypeTransportTicket {
        
        /// <remarks/>
        Delivery,
        
        /// <remarks/>
        Devolution,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/TransportTicket")]
    public partial class AxdTransportTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_TransportTicketTable[] transportTicketTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransportTicketTable", Order=3)]
        public AxdEntity_TransportTicketTable[] TransportTicketTable {
            get {
                return this.transportTicketTableField;
            }
            set {
                this.transportTicketTableField = value;
                this.RaisePropertyChanged("TransportTicketTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="tablaValesTransporte.TransportTicketService")]
    public interface TransportTicketService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (TransportTicketServiceReadRequest) del mensaje TransportTicketServiceReadRequest no coincide con el valor predeterminado (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportTicketService/read", ReplyAction="http://tempuri.org/TransportTicketService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaValesTransporte.AifFault), Action="http://tempuri.org/TransportTicketService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaValesTransporte.TransportTicketServiceReadResponse read(ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportTicketService/read", ReplyAction="http://tempuri.org/TransportTicketService/readResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceReadResponse> readAsync(ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (TransportTicketServiceFindKeysRequest) del mensaje TransportTicketServiceFindKeysRequest no coincide con el valor predeterminado (findKeys)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportTicketService/findKeys", ReplyAction="http://tempuri.org/TransportTicketService/findKeysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaValesTransporte.AifFault), Action="http://tempuri.org/TransportTicketService/findKeysAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysResponse findKeys(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportTicketService/findKeys", ReplyAction="http://tempuri.org/TransportTicketService/findKeysResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysResponse> findKeysAsync(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (TransportTicketServiceFindRequest) del mensaje TransportTicketServiceFindRequest no coincide con el valor predeterminado (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportTicketService/find", ReplyAction="http://tempuri.org/TransportTicketService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaValesTransporte.AifFault), Action="http://tempuri.org/TransportTicketService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaValesTransporte.TransportTicketServiceFindResponse find(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportTicketService/find", ReplyAction="http://tempuri.org/TransportTicketService/findResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceFindResponse> findAsync(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransportTicketServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TransportTicketServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaValesTransporte.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public ROP_Informe.tablaValesTransporte.EntityKey[] EntityKeyList;
        
        public TransportTicketServiceReadRequest() {
        }
        
        public TransportTicketServiceReadRequest(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransportTicketServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TransportTicketServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/TransportTicket", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/TransportTicket")]
        public ROP_Informe.tablaValesTransporte.AxdTransportTicket TransportTicket;
        
        public TransportTicketServiceReadResponse() {
        }
        
        public TransportTicketServiceReadResponse(ROP_Informe.tablaValesTransporte.AxdTransportTicket TransportTicket) {
            this.TransportTicket = TransportTicket;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransportTicketServiceFindKeysRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TransportTicketServiceFindKeysRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaValesTransporte.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria;
        
        public TransportTicketServiceFindKeysRequest() {
        }
        
        public TransportTicketServiceFindKeysRequest(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransportTicketServiceFindKeysResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TransportTicketServiceFindKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public ROP_Informe.tablaValesTransporte.EntityKey[] EntityKeyList;
        
        public TransportTicketServiceFindKeysResponse() {
        }
        
        public TransportTicketServiceFindKeysResponse(ROP_Informe.tablaValesTransporte.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransportTicketServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TransportTicketServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaValesTransporte.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria;
        
        public TransportTicketServiceFindRequest() {
        }
        
        public TransportTicketServiceFindRequest(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransportTicketServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TransportTicketServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/TransportTicket", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/TransportTicket")]
        public ROP_Informe.tablaValesTransporte.AxdTransportTicket TransportTicket;
        
        public TransportTicketServiceFindResponse() {
        }
        
        public TransportTicketServiceFindResponse(ROP_Informe.tablaValesTransporte.AxdTransportTicket TransportTicket) {
            this.TransportTicket = TransportTicket;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransportTicketServiceChannel : ROP_Informe.tablaValesTransporte.TransportTicketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportTicketServiceClient : System.ServiceModel.ClientBase<ROP_Informe.tablaValesTransporte.TransportTicketService>, ROP_Informe.tablaValesTransporte.TransportTicketService {
        
        public TransportTicketServiceClient() {
        }
        
        public TransportTicketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportTicketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportTicketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportTicketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaValesTransporte.TransportTicketServiceReadResponse ROP_Informe.tablaValesTransporte.TransportTicketService.read(ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public ROP_Informe.tablaValesTransporte.AxdTransportTicket read(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.EntityKey[] EntityKeyList) {
            ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest inValue = new ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            ROP_Informe.tablaValesTransporte.TransportTicketServiceReadResponse retVal = ((ROP_Informe.tablaValesTransporte.TransportTicketService)(this)).read(inValue);
            return retVal.TransportTicket;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceReadResponse> ROP_Informe.tablaValesTransporte.TransportTicketService.readAsync(ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceReadResponse> readAsync(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.EntityKey[] EntityKeyList) {
            ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest inValue = new ROP_Informe.tablaValesTransporte.TransportTicketServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((ROP_Informe.tablaValesTransporte.TransportTicketService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysResponse ROP_Informe.tablaValesTransporte.TransportTicketService.findKeys(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest request) {
            return base.Channel.findKeys(request);
        }
        
        public ROP_Informe.tablaValesTransporte.EntityKey[] findKeys(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest inValue = new ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysResponse retVal = ((ROP_Informe.tablaValesTransporte.TransportTicketService)(this)).findKeys(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysResponse> ROP_Informe.tablaValesTransporte.TransportTicketService.findKeysAsync(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest request) {
            return base.Channel.findKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysResponse> findKeysAsync(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest inValue = new ROP_Informe.tablaValesTransporte.TransportTicketServiceFindKeysRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((ROP_Informe.tablaValesTransporte.TransportTicketService)(this)).findKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaValesTransporte.TransportTicketServiceFindResponse ROP_Informe.tablaValesTransporte.TransportTicketService.find(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public ROP_Informe.tablaValesTransporte.AxdTransportTicket find(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest inValue = new ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            ROP_Informe.tablaValesTransporte.TransportTicketServiceFindResponse retVal = ((ROP_Informe.tablaValesTransporte.TransportTicketService)(this)).find(inValue);
            return retVal.TransportTicket;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceFindResponse> ROP_Informe.tablaValesTransporte.TransportTicketService.findAsync(ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaValesTransporte.TransportTicketServiceFindResponse> findAsync(ROP_Informe.tablaValesTransporte.CallContext CallContext, ROP_Informe.tablaValesTransporte.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest inValue = new ROP_Informe.tablaValesTransporte.TransportTicketServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((ROP_Informe.tablaValesTransporte.TransportTicketService)(this)).findAsync(inValue);
        }
    }
}
