//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_Informe.tablaAlbaranesEntrega {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking")]
    public partial class AxdEntity_CustPackingSlipJour : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string costCenterField;
        
        private string delegationField;
        
        private System.Nullable<System.DateTime> deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private string packingSlipIdField;
        
        private string salesIdField;
        
        private System.Nullable<AxdEnum_SalesType> salesTypeField;
        
        private bool salesTypeFieldSpecified;
        
        private System.Nullable<AxdEnum_TiposAlquiler> tipoAlquilerField;
        
        private bool tipoAlquilerFieldSpecified;
        
        private System.Nullable<AxdEnum_TiposVentas> tipoVentaField;
        
        private bool tipoVentaFieldSpecified;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_CustPackingSlipJour() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CostCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
                this.RaisePropertyChanged("CostCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Delegation {
            get {
                return this.delegationField;
            }
            set {
                this.delegationField = value;
                this.RaisePropertyChanged("Delegation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
                this.RaisePropertyChanged("DeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string PackingSlipId {
            get {
                return this.packingSlipIdField;
            }
            set {
                this.packingSlipIdField = value;
                this.RaisePropertyChanged("PackingSlipId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SalesId {
            get {
                return this.salesIdField;
            }
            set {
                this.salesIdField = value;
                this.RaisePropertyChanged("SalesId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<AxdEnum_SalesType> SalesType {
            get {
                return this.salesTypeField;
            }
            set {
                this.salesTypeField = value;
                this.RaisePropertyChanged("SalesType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesTypeSpecified {
            get {
                return this.salesTypeFieldSpecified;
            }
            set {
                this.salesTypeFieldSpecified = value;
                this.RaisePropertyChanged("SalesTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<AxdEnum_TiposAlquiler> TipoAlquiler {
            get {
                return this.tipoAlquilerField;
            }
            set {
                this.tipoAlquilerField = value;
                this.RaisePropertyChanged("TipoAlquiler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoAlquilerSpecified {
            get {
                return this.tipoAlquilerFieldSpecified;
            }
            set {
                this.tipoAlquilerFieldSpecified = value;
                this.RaisePropertyChanged("TipoAlquilerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<AxdEnum_TiposVentas> TipoVenta {
            get {
                return this.tipoVentaField;
            }
            set {
                this.tipoVentaField = value;
                this.RaisePropertyChanged("TipoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoVentaSpecified {
            get {
                return this.tipoVentaFieldSpecified;
            }
            set {
                this.tipoVentaFieldSpecified = value;
                this.RaisePropertyChanged("TipoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_SalesType {
        
        /// <remarks/>
        Journal,
        
        /// <remarks/>
        DEL_Quotation,
        
        /// <remarks/>
        Subscription,
        
        /// <remarks/>
        Sales,
        
        /// <remarks/>
        ReturnItem,
        
        /// <remarks/>
        DEL_Blanket,
        
        /// <remarks/>
        ItemReq,
        
        /// <remarks/>
        Alquiler,
        
        /// <remarks/>
        IBPTCashSales,
        
        /// <remarks/>
        IBPTSamples,
        
        /// <remarks/>
        IBPTSupplies,
        
        /// <remarks/>
        IBPTComplaint,
        
        /// <remarks/>
        IBPTForeigner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_TiposAlquiler {
        
        /// <remarks/>
        Puro,
        
        /// <remarks/>
        Amortizacion,
        
        /// <remarks/>
        OpcionCompra,
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Repair,
        
        /// <remarks/>
        Showroom,
        
        /// <remarks/>
        Intercompany,
        
        /// <remarks/>
        SIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_TiposVentas {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Usado,
        
        /// <remarks/>
        Liquidacion,
        
        /// <remarks/>
        Financial,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking")]
    public partial class AxdEntity_CustPackingSlipTrans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private System.DateTime deliveryDateField;
        
        private System.Nullable<decimal> inventQtyField;
        
        private bool inventQtyFieldSpecified;
        
        private string inventTransIdField;
        
        private string itemIdField;
        
        private string obraIdField;
        
        private string origSalesIdField;
        
        private string packingSlipIdField;
        
        private System.Nullable<decimal> qtyField;
        
        private bool qtyFieldSpecified;
        
        private string salesIdField;
        
        private AxdEntity_CustPackingSlipJour[] custPackingSlipJourField;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_CustPackingSlipTrans() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
                this.RaisePropertyChanged("DeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> InventQty {
            get {
                return this.inventQtyField;
            }
            set {
                this.inventQtyField = value;
                this.RaisePropertyChanged("InventQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventQtySpecified {
            get {
                return this.inventQtyFieldSpecified;
            }
            set {
                this.inventQtyFieldSpecified = value;
                this.RaisePropertyChanged("InventQtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string InventTransId {
            get {
                return this.inventTransIdField;
            }
            set {
                this.inventTransIdField = value;
                this.RaisePropertyChanged("InventTransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ObraId {
            get {
                return this.obraIdField;
            }
            set {
                this.obraIdField = value;
                this.RaisePropertyChanged("ObraId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string OrigSalesId {
            get {
                return this.origSalesIdField;
            }
            set {
                this.origSalesIdField = value;
                this.RaisePropertyChanged("OrigSalesId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PackingSlipId {
            get {
                return this.packingSlipIdField;
            }
            set {
                this.packingSlipIdField = value;
                this.RaisePropertyChanged("PackingSlipId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified {
            get {
                return this.qtyFieldSpecified;
            }
            set {
                this.qtyFieldSpecified = value;
                this.RaisePropertyChanged("QtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string SalesId {
            get {
                return this.salesIdField;
            }
            set {
                this.salesIdField = value;
                this.RaisePropertyChanged("SalesId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustPackingSlipJour", Order=10)]
        public AxdEntity_CustPackingSlipJour[] CustPackingSlipJour {
            get {
                return this.custPackingSlipJourField;
            }
            set {
                this.custPackingSlipJourField = value;
                this.RaisePropertyChanged("CustPackingSlipJour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking")]
    public partial class AxdCustPacking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_CustPackingSlipTrans[] custPackingSlipTransField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustPackingSlipTrans", Order=3)]
        public AxdEntity_CustPackingSlipTrans[] CustPackingSlipTrans {
            get {
                return this.custPackingSlipTransField;
            }
            set {
                this.custPackingSlipTransField = value;
                this.RaisePropertyChanged("CustPackingSlipTrans");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="tablaAlbaranesEntrega.CustPackingService")]
    public interface CustPackingService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CustPackingServiceFindRequest) del mensaje CustPackingServiceFindRequest no coincide con el valor predeterminado (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustPackingService/find", ReplyAction="http://tempuri.org/CustPackingService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaAlbaranesEntrega.AifFault), Action="http://tempuri.org/CustPackingService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindResponse find(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustPackingService/find", ReplyAction="http://tempuri.org/CustPackingService/findResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindResponse> findAsync(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CustPackingServiceFindKeysRequest) del mensaje CustPackingServiceFindKeysRequest no coincide con el valor predeterminado (findKeys)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustPackingService/findKeys", ReplyAction="http://tempuri.org/CustPackingService/findKeysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaAlbaranesEntrega.AifFault), Action="http://tempuri.org/CustPackingService/findKeysAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysResponse findKeys(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustPackingService/findKeys", ReplyAction="http://tempuri.org/CustPackingService/findKeysResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysResponse> findKeysAsync(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CustPackingServiceReadRequest) del mensaje CustPackingServiceReadRequest no coincide con el valor predeterminado (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustPackingService/read", ReplyAction="http://tempuri.org/CustPackingService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaAlbaranesEntrega.AifFault), Action="http://tempuri.org/CustPackingService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadResponse read(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustPackingService/read", ReplyAction="http://tempuri.org/CustPackingService/readResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadResponse> readAsync(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustPackingServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CustPackingServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria;
        
        public CustPackingServiceFindRequest() {
        }
        
        public CustPackingServiceFindRequest(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustPackingServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CustPackingServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking")]
        public ROP_Informe.tablaAlbaranesEntrega.AxdCustPacking CustPacking;
        
        public CustPackingServiceFindResponse() {
        }
        
        public CustPackingServiceFindResponse(ROP_Informe.tablaAlbaranesEntrega.AxdCustPacking CustPacking) {
            this.CustPacking = CustPacking;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustPackingServiceFindKeysRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CustPackingServiceFindKeysRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria;
        
        public CustPackingServiceFindKeysRequest() {
        }
        
        public CustPackingServiceFindKeysRequest(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustPackingServiceFindKeysResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CustPackingServiceFindKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public ROP_Informe.tablaAlbaranesEntrega.EntityKey[] EntityKeyList;
        
        public CustPackingServiceFindKeysResponse() {
        }
        
        public CustPackingServiceFindKeysResponse(ROP_Informe.tablaAlbaranesEntrega.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustPackingServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CustPackingServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public ROP_Informe.tablaAlbaranesEntrega.EntityKey[] EntityKeyList;
        
        public CustPackingServiceReadRequest() {
        }
        
        public CustPackingServiceReadRequest(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustPackingServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CustPackingServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/CustPacking")]
        public ROP_Informe.tablaAlbaranesEntrega.AxdCustPacking CustPacking;
        
        public CustPackingServiceReadResponse() {
        }
        
        public CustPackingServiceReadResponse(ROP_Informe.tablaAlbaranesEntrega.AxdCustPacking CustPacking) {
            this.CustPacking = CustPacking;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustPackingServiceChannel : ROP_Informe.tablaAlbaranesEntrega.CustPackingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustPackingServiceClient : System.ServiceModel.ClientBase<ROP_Informe.tablaAlbaranesEntrega.CustPackingService>, ROP_Informe.tablaAlbaranesEntrega.CustPackingService {
        
        public CustPackingServiceClient() {
        }
        
        public CustPackingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustPackingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustPackingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustPackingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindResponse ROP_Informe.tablaAlbaranesEntrega.CustPackingService.find(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public ROP_Informe.tablaAlbaranesEntrega.AxdCustPacking find(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest inValue = new ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindResponse retVal = ((ROP_Informe.tablaAlbaranesEntrega.CustPackingService)(this)).find(inValue);
            return retVal.CustPacking;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindResponse> ROP_Informe.tablaAlbaranesEntrega.CustPackingService.findAsync(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindResponse> findAsync(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest inValue = new ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((ROP_Informe.tablaAlbaranesEntrega.CustPackingService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysResponse ROP_Informe.tablaAlbaranesEntrega.CustPackingService.findKeys(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest request) {
            return base.Channel.findKeys(request);
        }
        
        public ROP_Informe.tablaAlbaranesEntrega.EntityKey[] findKeys(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest inValue = new ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysResponse retVal = ((ROP_Informe.tablaAlbaranesEntrega.CustPackingService)(this)).findKeys(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysResponse> ROP_Informe.tablaAlbaranesEntrega.CustPackingService.findKeysAsync(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest request) {
            return base.Channel.findKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysResponse> findKeysAsync(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest inValue = new ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceFindKeysRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((ROP_Informe.tablaAlbaranesEntrega.CustPackingService)(this)).findKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadResponse ROP_Informe.tablaAlbaranesEntrega.CustPackingService.read(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public ROP_Informe.tablaAlbaranesEntrega.AxdCustPacking read(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.EntityKey[] EntityKeyList) {
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest inValue = new ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadResponse retVal = ((ROP_Informe.tablaAlbaranesEntrega.CustPackingService)(this)).read(inValue);
            return retVal.CustPacking;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadResponse> ROP_Informe.tablaAlbaranesEntrega.CustPackingService.readAsync(ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadResponse> readAsync(ROP_Informe.tablaAlbaranesEntrega.CallContext CallContext, ROP_Informe.tablaAlbaranesEntrega.EntityKey[] EntityKeyList) {
            ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest inValue = new ROP_Informe.tablaAlbaranesEntrega.CustPackingServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((ROP_Informe.tablaAlbaranesEntrega.CustPackingService)(this)).readAsync(inValue);
        }
    }
}
