//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_Informe.tablaInventario {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans")]
    public partial class AxdEntity_InventTransOrigin_1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inventTransIdField;
        
        private System.Nullable<AxdEnum_InventTransType> referenceCategoryField;
        
        private bool referenceCategoryFieldSpecified;
        
        private string referenceIdField;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_InventTransOrigin_1() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string InventTransId {
            get {
                return this.inventTransIdField;
            }
            set {
                this.inventTransIdField = value;
                this.RaisePropertyChanged("InventTransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_InventTransType> ReferenceCategory {
            get {
                return this.referenceCategoryField;
            }
            set {
                this.referenceCategoryField = value;
                this.RaisePropertyChanged("ReferenceCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceCategorySpecified {
            get {
                return this.referenceCategoryFieldSpecified;
            }
            set {
                this.referenceCategoryFieldSpecified = value;
                this.RaisePropertyChanged("ReferenceCategorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_InventTransType {
        
        /// <remarks/>
        Sales,
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        Purch,
        
        /// <remarks/>
        InventTransaction,
        
        /// <remarks/>
        InventLossProfit,
        
        /// <remarks/>
        InventTransfer,
        
        /// <remarks/>
        SummedUp,
        
        /// <remarks/>
        ProdLine,
        
        /// <remarks/>
        BOMLine,
        
        /// <remarks/>
        BOMMain,
        
        /// <remarks/>
        WMSOrder,
        
        /// <remarks/>
        Project,
        
        /// <remarks/>
        InventCounting,
        
        /// <remarks/>
        WMSTransport,
        
        /// <remarks/>
        QuarantineOrder,
        
        /// <remarks/>
        Asset,
        
        /// <remarks/>
        TransferOrderShip,
        
        /// <remarks/>
        TransferOrderReceive,
        
        /// <remarks/>
        TransferOrderScrap,
        
        /// <remarks/>
        SalesQuotation,
        
        /// <remarks/>
        QualityOrder,
        
        /// <remarks/>
        Blocking,
        
        /// <remarks/>
        KanbanJobProcess,
        
        /// <remarks/>
        KanbanJobTransferReceipt,
        
        /// <remarks/>
        KanbanJobTransferIssue,
        
        /// <remarks/>
        KanbanJobPickingList,
        
        /// <remarks/>
        KanbanJobWIP,
        
        /// <remarks/>
        KanbanEmptied,
        
        /// <remarks/>
        PmfProdCoBy,
        
        /// <remarks/>
        ProdRelease_RU,
        
        /// <remarks/>
        FixedAssets_RU,
        
        /// <remarks/>
        Statement,
        
        /// <remarks/>
        WorkPaperPalet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans")]
    public partial class AxdEntity_InventTrans_1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private System.Nullable<decimal> canonFenolicoField;
        
        private bool canonFenolicoFieldSpecified;
        
        private System.Nullable<decimal> canonFenolicoOrigField;
        
        private bool canonFenolicoOrigFieldSpecified;
        
        private System.Nullable<decimal> canonImportField;
        
        private bool canonImportFieldSpecified;
        
        private System.Nullable<decimal> canonImportOrigField;
        
        private bool canonImportOrigFieldSpecified;
        
        private System.Nullable<decimal> eurDiaField;
        
        private bool eurDiaFieldSpecified;
        
        private System.Nullable<decimal> eurDiaOrigField;
        
        private bool eurDiaOrigFieldSpecified;
        
        private string inventLocationIdField;
        
        private System.Nullable<AxdEnum_InventTransMovementType> inventTransMovementTypeField;
        
        private bool inventTransMovementTypeFieldSpecified;
        
        private string itemIdField;
        
        private string obraIdField;
        
        private System.Nullable<decimal> qtyField;
        
        private bool qtyFieldSpecified;
        
        private System.Nullable<System.DateTime> valueDateField;
        
        private bool valueDateFieldSpecified;
        
        private System.Nullable<System.DateTime> valueDateCashFlowField;
        
        private bool valueDateCashFlowFieldSpecified;
        
        private string valuePackingSlipField;
        
        private AxdEntity_InventTransOrigin_1[] inventTransOrigin_1Field;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_InventTrans_1() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> CanonFenolico {
            get {
                return this.canonFenolicoField;
            }
            set {
                this.canonFenolicoField = value;
                this.RaisePropertyChanged("CanonFenolico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanonFenolicoSpecified {
            get {
                return this.canonFenolicoFieldSpecified;
            }
            set {
                this.canonFenolicoFieldSpecified = value;
                this.RaisePropertyChanged("CanonFenolicoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> CanonFenolicoOrig {
            get {
                return this.canonFenolicoOrigField;
            }
            set {
                this.canonFenolicoOrigField = value;
                this.RaisePropertyChanged("CanonFenolicoOrig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanonFenolicoOrigSpecified {
            get {
                return this.canonFenolicoOrigFieldSpecified;
            }
            set {
                this.canonFenolicoOrigFieldSpecified = value;
                this.RaisePropertyChanged("CanonFenolicoOrigSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> CanonImport {
            get {
                return this.canonImportField;
            }
            set {
                this.canonImportField = value;
                this.RaisePropertyChanged("CanonImport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanonImportSpecified {
            get {
                return this.canonImportFieldSpecified;
            }
            set {
                this.canonImportFieldSpecified = value;
                this.RaisePropertyChanged("CanonImportSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> CanonImportOrig {
            get {
                return this.canonImportOrigField;
            }
            set {
                this.canonImportOrigField = value;
                this.RaisePropertyChanged("CanonImportOrig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanonImportOrigSpecified {
            get {
                return this.canonImportOrigFieldSpecified;
            }
            set {
                this.canonImportOrigFieldSpecified = value;
                this.RaisePropertyChanged("CanonImportOrigSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> EurDia {
            get {
                return this.eurDiaField;
            }
            set {
                this.eurDiaField = value;
                this.RaisePropertyChanged("EurDia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EurDiaSpecified {
            get {
                return this.eurDiaFieldSpecified;
            }
            set {
                this.eurDiaFieldSpecified = value;
                this.RaisePropertyChanged("EurDiaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> EurDiaOrig {
            get {
                return this.eurDiaOrigField;
            }
            set {
                this.eurDiaOrigField = value;
                this.RaisePropertyChanged("EurDiaOrig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EurDiaOrigSpecified {
            get {
                return this.eurDiaOrigFieldSpecified;
            }
            set {
                this.eurDiaOrigFieldSpecified = value;
                this.RaisePropertyChanged("EurDiaOrigSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string InventLocationId {
            get {
                return this.inventLocationIdField;
            }
            set {
                this.inventLocationIdField = value;
                this.RaisePropertyChanged("InventLocationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<AxdEnum_InventTransMovementType> InventTransMovementType {
            get {
                return this.inventTransMovementTypeField;
            }
            set {
                this.inventTransMovementTypeField = value;
                this.RaisePropertyChanged("InventTransMovementType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventTransMovementTypeSpecified {
            get {
                return this.inventTransMovementTypeFieldSpecified;
            }
            set {
                this.inventTransMovementTypeFieldSpecified = value;
                this.RaisePropertyChanged("InventTransMovementTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string ObraId {
            get {
                return this.obraIdField;
            }
            set {
                this.obraIdField = value;
                this.RaisePropertyChanged("ObraId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified {
            get {
                return this.qtyFieldSpecified;
            }
            set {
                this.qtyFieldSpecified = value;
                this.RaisePropertyChanged("QtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> ValueDate {
            get {
                return this.valueDateField;
            }
            set {
                this.valueDateField = value;
                this.RaisePropertyChanged("ValueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueDateSpecified {
            get {
                return this.valueDateFieldSpecified;
            }
            set {
                this.valueDateFieldSpecified = value;
                this.RaisePropertyChanged("ValueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> ValueDateCashFlow {
            get {
                return this.valueDateCashFlowField;
            }
            set {
                this.valueDateCashFlowField = value;
                this.RaisePropertyChanged("ValueDateCashFlow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueDateCashFlowSpecified {
            get {
                return this.valueDateCashFlowFieldSpecified;
            }
            set {
                this.valueDateCashFlowFieldSpecified = value;
                this.RaisePropertyChanged("ValueDateCashFlowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string ValuePackingSlip {
            get {
                return this.valuePackingSlipField;
            }
            set {
                this.valuePackingSlipField = value;
                this.RaisePropertyChanged("ValuePackingSlip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InventTransOrigin_1", Order=15)]
        public AxdEntity_InventTransOrigin_1[] InventTransOrigin_1 {
            get {
                return this.inventTransOrigin_1Field;
            }
            set {
                this.inventTransOrigin_1Field = value;
                this.RaisePropertyChanged("InventTransOrigin_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_InventTransMovementType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        PurchThirdPartyIn,
        
        /// <remarks/>
        PurchIntercompanyIn,
        
        /// <remarks/>
        SalesThirdPartyOut,
        
        /// <remarks/>
        SalesIntercompanyOut,
        
        /// <remarks/>
        SalesThirdPartyOutOtherDeleg,
        
        /// <remarks/>
        RentDeliveryOut,
        
        /// <remarks/>
        RentDeliveryIn,
        
        /// <remarks/>
        RentDeliveryOutOtherDeleg,
        
        /// <remarks/>
        RentDevolutionOut,
        
        /// <remarks/>
        RentDevolutionIn,
        
        /// <remarks/>
        RentDevolutionInOtherDeleg,
        
        /// <remarks/>
        SalesJobsiteOut,
        
        /// <remarks/>
        LostJobsiteOut,
        
        /// <remarks/>
        TransferOut,
        
        /// <remarks/>
        TransferIn,
        
        /// <remarks/>
        InternalProductionOut,
        
        /// <remarks/>
        InternalProductionIn,
        
        /// <remarks/>
        ExternalProductionOut,
        
        /// <remarks/>
        ExternalProductionIn,
        
        /// <remarks/>
        InternalRepairOut,
        
        /// <remarks/>
        InternalRepairIn,
        
        /// <remarks/>
        ExternalRepairIn,
        
        /// <remarks/>
        ExternalRepairOutput,
        
        /// <remarks/>
        RentDevolutionScrapOut,
        
        /// <remarks/>
        RentDevolutionScrapIn,
        
        /// <remarks/>
        RentDevolutionScrapInOtherDeleg,
        
        /// <remarks/>
        InternalRepairScrapOut,
        
        /// <remarks/>
        InternalRepairScrapIn,
        
        /// <remarks/>
        ExternalRepairScrapOut,
        
        /// <remarks/>
        ExternalRepairScrapIn,
        
        /// <remarks/>
        IntTransferOut,
        
        /// <remarks/>
        IntTransferIn,
        
        /// <remarks/>
        VendTransferOut,
        
        /// <remarks/>
        VendTransferIn,
        
        /// <remarks/>
        Count,
        
        /// <remarks/>
        PackagingRearmament,
        
        /// <remarks/>
        Migration,
        
        /// <remarks/>
        ConsumptionOut,
        
        /// <remarks/>
        SummedUpOut,
        
        /// <remarks/>
        SummedUpIn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans")]
    public partial class AxdInventTrans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_InventTrans_1[] inventTrans_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InventTrans_1", Order=3)]
        public AxdEntity_InventTrans_1[] InventTrans_1 {
            get {
                return this.inventTrans_1Field;
            }
            set {
                this.inventTrans_1Field = value;
                this.RaisePropertyChanged("InventTrans_1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="tablaInventario.InventTransOriginService")]
    public interface InventTransOriginService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (InventTransOriginServiceReadRequest) del mensaje InventTransOriginServiceReadRequest no coincide con el valor predeterminado (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventTransOriginService/read", ReplyAction="http://tempuri.org/InventTransOriginService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaInventario.AifFault), Action="http://tempuri.org/InventTransOriginService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaInventario.InventTransOriginServiceReadResponse read(ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventTransOriginService/read", ReplyAction="http://tempuri.org/InventTransOriginService/readResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceReadResponse> readAsync(ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (InventTransOriginServiceFindRequest) del mensaje InventTransOriginServiceFindRequest no coincide con el valor predeterminado (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventTransOriginService/find", ReplyAction="http://tempuri.org/InventTransOriginService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaInventario.AifFault), Action="http://tempuri.org/InventTransOriginService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaInventario.InventTransOriginServiceFindResponse find(ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventTransOriginService/find", ReplyAction="http://tempuri.org/InventTransOriginService/findResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceFindResponse> findAsync(ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (InventTransOriginServiceFindKeysRequest) del mensaje InventTransOriginServiceFindKeysRequest no coincide con el valor predeterminado (findKeys)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventTransOriginService/findKeys", ReplyAction="http://tempuri.org/InventTransOriginService/findKeysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ROP_Informe.tablaInventario.AifFault), Action="http://tempuri.org/InventTransOriginService/findKeysAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysResponse findKeys(ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventTransOriginService/findKeys", ReplyAction="http://tempuri.org/InventTransOriginService/findKeysResponse")]
        System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysResponse> findKeysAsync(ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InventTransOriginServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class InventTransOriginServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaInventario.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public ROP_Informe.tablaInventario.EntityKey[] EntityKeyList;
        
        public InventTransOriginServiceReadRequest() {
        }
        
        public InventTransOriginServiceReadRequest(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InventTransOriginServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class InventTransOriginServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans")]
        public ROP_Informe.tablaInventario.AxdInventTrans InventTrans;
        
        public InventTransOriginServiceReadResponse() {
        }
        
        public InventTransOriginServiceReadResponse(ROP_Informe.tablaInventario.AxdInventTrans InventTrans) {
            this.InventTrans = InventTrans;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InventTransOriginServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class InventTransOriginServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaInventario.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public ROP_Informe.tablaInventario.QueryCriteria QueryCriteria;
        
        public InventTransOriginServiceFindRequest() {
        }
        
        public InventTransOriginServiceFindRequest(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InventTransOriginServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class InventTransOriginServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/InventTrans")]
        public ROP_Informe.tablaInventario.AxdInventTrans InventTrans;
        
        public InventTransOriginServiceFindResponse() {
        }
        
        public InventTransOriginServiceFindResponse(ROP_Informe.tablaInventario.AxdInventTrans InventTrans) {
            this.InventTrans = InventTrans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InventTransOriginServiceFindKeysRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class InventTransOriginServiceFindKeysRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ROP_Informe.tablaInventario.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public ROP_Informe.tablaInventario.QueryCriteria QueryCriteria;
        
        public InventTransOriginServiceFindKeysRequest() {
        }
        
        public InventTransOriginServiceFindKeysRequest(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InventTransOriginServiceFindKeysResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class InventTransOriginServiceFindKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public ROP_Informe.tablaInventario.EntityKey[] EntityKeyList;
        
        public InventTransOriginServiceFindKeysResponse() {
        }
        
        public InventTransOriginServiceFindKeysResponse(ROP_Informe.tablaInventario.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventTransOriginServiceChannel : ROP_Informe.tablaInventario.InventTransOriginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventTransOriginServiceClient : System.ServiceModel.ClientBase<ROP_Informe.tablaInventario.InventTransOriginService>, ROP_Informe.tablaInventario.InventTransOriginService {
        
        public InventTransOriginServiceClient() {
        }
        
        public InventTransOriginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventTransOriginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventTransOriginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventTransOriginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaInventario.InventTransOriginServiceReadResponse ROP_Informe.tablaInventario.InventTransOriginService.read(ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public ROP_Informe.tablaInventario.AxdInventTrans read(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.EntityKey[] EntityKeyList) {
            ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest inValue = new ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            ROP_Informe.tablaInventario.InventTransOriginServiceReadResponse retVal = ((ROP_Informe.tablaInventario.InventTransOriginService)(this)).read(inValue);
            return retVal.InventTrans;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceReadResponse> ROP_Informe.tablaInventario.InventTransOriginService.readAsync(ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceReadResponse> readAsync(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.EntityKey[] EntityKeyList) {
            ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest inValue = new ROP_Informe.tablaInventario.InventTransOriginServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((ROP_Informe.tablaInventario.InventTransOriginService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaInventario.InventTransOriginServiceFindResponse ROP_Informe.tablaInventario.InventTransOriginService.find(ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public ROP_Informe.tablaInventario.AxdInventTrans find(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest inValue = new ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            ROP_Informe.tablaInventario.InventTransOriginServiceFindResponse retVal = ((ROP_Informe.tablaInventario.InventTransOriginService)(this)).find(inValue);
            return retVal.InventTrans;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceFindResponse> ROP_Informe.tablaInventario.InventTransOriginService.findAsync(ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceFindResponse> findAsync(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest inValue = new ROP_Informe.tablaInventario.InventTransOriginServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((ROP_Informe.tablaInventario.InventTransOriginService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysResponse ROP_Informe.tablaInventario.InventTransOriginService.findKeys(ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest request) {
            return base.Channel.findKeys(request);
        }
        
        public ROP_Informe.tablaInventario.EntityKey[] findKeys(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest inValue = new ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysResponse retVal = ((ROP_Informe.tablaInventario.InventTransOriginService)(this)).findKeys(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysResponse> ROP_Informe.tablaInventario.InventTransOriginService.findKeysAsync(ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest request) {
            return base.Channel.findKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysResponse> findKeysAsync(ROP_Informe.tablaInventario.CallContext CallContext, ROP_Informe.tablaInventario.QueryCriteria QueryCriteria) {
            ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest inValue = new ROP_Informe.tablaInventario.InventTransOriginServiceFindKeysRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((ROP_Informe.tablaInventario.InventTransOriginService)(this)).findKeysAsync(inValue);
        }
    }
}
